### ISSUE TITLE
Grate is unneccessary now

### ISSUE THREAD

**Issue by zspecza** [carrot/grate#5]
Cory has done something truly amazing with his [latest changes to Jeet](https://github.com/mojotech/jeet/blob/master/CHANGELOG.md#500) that kinda renders Grate obsolete :P

**Comment by jescalan** [comment]
While this certainly could be true and we'll probably switch to using jeet, grate is going to be kept up to date as a mirror/backup just because jeet has a history of drastic and sudden changes. Now that grate is something we rely on for a good number or projects within my company, we need to be 100% sure that we can get something stable if needed.

That being said, I will make a note in the readme pointing to jeet as the preferred option shortly and close this issue with that commit :grinning:

**Comment by zspecza** [comment]
:+1:
